---
title: "BHao_Assign4"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
setwd("~/Google Drive/CUNY/git/DATA605/HW4")
```

##Problem Set 1  

```{r}
A = matrix(c(1,2,3,-1,0,4), 2, 3, byrow = TRUE)  # create matrix A  
X = A %*% t(A)  # matrix X = AAt
Y = t(A) %*% A  # matrix Y = AtA
U = eigen(X)$vectors  # matrix U = eigenvectors of X  
V = eigen(Y)$vectors  # matrix V = eigenvectors of Y  
D = eigen(X)$values  # D = eigenvalues of X and Y 

d = svd(A)$d  # squareroots of eigenvalues of X and Y 
u = svd(A)$u  # eigenvectors of X as per svd function 
v = svd(A)$v  # eigenvectors of Y as per svd function 

# The left singular vectors of A (u) are indeed equal to the eigenvectors 
# of X (U) (with the signs of the # left column reversed)
u 
U

# The right singular vectors of A (v) are indeed qual to the eigenvectors 
# of Y (V) (with the signs of the # left column reversed). Addtionally, the 
# 3rd column of V is not relevant as there are only 2 eigenvalues.
v
V

# The squares of the singular values of A (d) are indeed equal to the 
# eigenvalues of X and Y (D) 
d^2
D
```

##Problem Set 2

```{r}
A = matrix(c(1,3,5,8,2,3,5,2,6,2,4,5,1,3,7,8), nrow = 4)

myinverse = function(A) {
  C = matrix(rep(0, length(A)), nrow(A), ncol(A))
  for (j in 1:ncol(A)) {
    for (i in 1:nrow(A)) {
      C[i, j] = (-1)^(i+j) * det(A[-i, -j])
    }
  }
  return(t(C) / det(A))
}
B = myinverse(A)
A %*% B
round(A %*% B, 6)
```


