---
title: "BHao_Assign9"
output: html_document
---

```{r setup, include=FALSE}
setwd("~/Google Drive/CUNY/git/DATA605/HW9")
```

##Problem Set 1  

1.1)  

```{r}
func1 = function(x) {
  x[0 <= x & x <= 1] = x[0 <= x & x <= 1]
  x[1 <  x & x <= 2] = 2 - x[1 <  x & x <= 2]
  return(x)
}

set.seed(123)
x = runif(100, 0, 2)
plot(x, func1(x))
```

1.2)  

```{r}
func2 = function(x) {
  x[0 <= x & x <= 1] = 1 - x[0 <=x & x <= 1]
  x[1 <  x & x <= 2] = x[1 <  x & x <= 2] - 1
  return(x)
}

set.seed(123)
x = runif(100, 0, 2)
plot(x, func2(x))
```

1.3)  

```{r}
set.seed(123)

x = runif(1000000, 0, 2)
hist(sample(x, 1000, prob = func1(x), replace = TRUE))  # insert distribution functions into prob argument of sample function 
hist(sample(x, 1000, prob = func2(x), replace = TRUE))  # insert distribution functions into prob argument of sample function 
```

1.4)  

```{r}
plot_means = function(n, func) {
  results = NULL  # initialize
  for (i in 1:1000) {
    x = runif(10000, 0, 2)
    samps = sample(x, n, prob = func(x), replace = TRUE)
    results = c(results, mean(samps))
  }
  hist(results)
}
```

1.5)  

```{r fig.width=10}
par(mfrow = c(1, 2))
plot_means(20, func1)
plot_means(20, func2)
```

