---
title: "BHao_Assign13"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
setwd("C:/Users/bhao/Google Drive/CUNY/git/DATA605/HW13")
```

```{r}
# derivative of f(x) = x^3 + 2x^2
# analytical solution = 3x^2 + 4x
deriv_func = function(x) {
  h = 1e-6
  up = (x + h)^3 + 2*(x + h)^2
  down = (x - h)^3 + 2*(x - h)^2
  return(slope = (up - down) / (2*h))
}

deriv_func(4)

# integral of f(x) = 3x^2 + 4x in the range [1,3] using intervals 1e-6
integ_func = function() {
  h = 1e-6
  area = 0
  for (x in seq(1, 3, h)) {
    area = area + h * (3*x^2 + 4*x)
  }
  return(area)
}

integ_func()
```

###Problem 3  

$$\int \sin(x)\cos(x)dx$$
$$u = \sin(x)$$  
$$du = \cos(x) dx$$  
$$dx = du / cos(x)$$
$$\int u \cos(x) du/\cos(x)$$
$$\int u ~du$$
$$\frac{1}{2} u^2$$
$$\frac{1}{2} \sin^2(x)$$

###Problem 4  

$$\int x^2 e^x dx$$
$$u = x^2$$ 
$$du = 2x~dx$$
$$v = e^x$$
$$dv = e^x dx$$
$$x^2e^x - 2\int x~e^x~dx$$
$$substitute~again$$  
$$x^2e^x - 2(xe^x - e^x)$$
$$e^x(x^2 - 2x - 2)$$

###Problem 5  

$$\frac{d}{dx} (x\cos(x))$$
$$\cos(x) - x\sin(x)$$
###Problem 6  

$$\frac{d}{dx} e^{x^4}$$
$$e^{x^4} (\frac{d}{dx} x^4)$$
$$e^{x^4} 4x^3$$

