---
title: "BHao_Assign3"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
setwd("~/Google Drive/CUNY/git/DATA605/HW3")
```

##Problem Set 1  

1) The rank of a matrix is equal to the number of pivot columns  

* First, convert **X** to **U**  

$$\mathbf{X} = \left[\begin{array}
{rrrr}
1 & 2 & 3 & 4 \\
-1 & 0 & 1 & 3 \\
0 & 1 & -2 & 1 \\
5 & 4 & -2 & -3 \\
\end{array}\right]
$$

* Swaps rows 2 and 3  

$$\mathbf{X} = \left[\begin{array}
{rrrr}
1 & 2 & 3 & 4 \\
0 & 1 & -2 & 1 \\
-1 & 0 & 1 & 3 \\
5 & 4 & -2 & -3 \\
\end{array}\right]
$$

* Add row 1 to row 3  

$$\mathbf{X} = \left[\begin{array}
{rrrr}
1 & 2 & 3 & 4 \\
0 & 1 & -2 & 1 \\
0 & 2 & 4 & 7 \\
5 & 4 & -2 & -3 \\
\end{array}\right]
$$

* Subtract 2 times row 2 from row 3  

$$\mathbf{X} = \left[\begin{array}
{rrrr}
1 & 2 & 3 & 4 \\
0 & 1 & -2 & 1 \\
0 & 0 & 8 & 5 \\
5 & 4 & -2 & -3 \\
\end{array}\right]
$$

* Subtract 5 times row 1 from row 4  

$$\mathbf{X} = \left[\begin{array}
{rrrr}
1 & 2 & 3 & 4 \\
0 & 1 & -2 & 1 \\
0 & 0 & 8 & 5 \\
0 & -6 & -17 & -23 \\
\end{array}\right]
$$

* Add 6 times row 2 to row 4  

$$\mathbf{X} = \left[\begin{array}
{rrrr}
1 & 2 & 3 & 4 \\
0 & 1 & -2 & 1 \\
0 & 0 & 8 & 5 \\
0 & 0 & -29 & -17 \\
\end{array}\right]
$$

* Add 29/8 times row 3 to row 4  

$$\mathbf{U} = \left[\begin{array}
{rrrr}
1 & 2 & 3 & 4 \\
0 & 1 & -2 & 1 \\
0 & 0 & 8 & 5 \\
0 & 0 & 0 & 9/8 \\
\end{array}\right]
$$

**U** contains 4 pivot columns; as such **X** and **U** have a rank equal to 4  

2) Maximum rank = n; minimum rank = 1  

3) Columns 2 and 3 are multiples of column 1 and thus cannot be pivot columns; as such, there is only 1 pivot column, and the rank of **B** is equal to 1. The elimination process below will demonstrate the same result.   

* Convert **B** to **U**  

$$\mathbf{B} = \left[\begin{array}
{rrrr}
1 & 2 & 1 \\
3 & 6 & 3 \\
2 & 4 & 2 \\
\end{array}\right]
$$

* Subtract 3 times row 1 from row 2; subtract 2 times row 1 from row 3  

$$\mathbf{U} = \left[\begin{array}
{rrrr}
1 & 2 & 1 \\
0 & 0 & 0 \\
0 & 0 & 0 \\
\end{array}\right]
$$

## Problem Set 2  

To find the eigenvalues, solve det($\lambda$I - A) = 0.   

$$\left[\begin{array}
{rrrrr}
\lambda-1 & -2 & -3 & \lambda - 1 & - 2 \\
0 & \lambda - 4 & -5 & 0 & \lambda - 4\\
0 & 0 & \lambda - 6 & 0 & 0 \\
\end{array}\right]
$$

Add left-to-right diagonals and subtract right-to-left diagonals to get the characteristic polynomial $$(\lambda - 1) (\lambda - 4) (\lambda - 6) or \lambda = 1, 4, 6$$

For $\lambda_1$ = 6, solve the following for **v**  

$$\left[\begin{array}
{rrrr}
5 & -2 & -3 \\
0 & 2 & -5 \\
0 & 0 & 0 \\
\end{array}\right]
\left[\begin{array}
{rrrr}
v_1 \\
v_2 \\
v_3 \\
\end{array}\right]
=
\left[\begin{array}
{rrrr}
0 \\
0 \\
0 \\
\end{array}\right]
$$

$$\mathbf{v} = \left[\begin{array}
{rrrr}
16 \\
25 \\
10 \\
\end{array}\right]
$$

For $\lambda_1$ = 4, solve the following for **v**  

$$\left[\begin{array}
{rrrr}
3 & -2 & -3 \\
0 & 0 & -5 \\
0 & 0 & -2 \\
\end{array}\right]
\left[\begin{array}
{rrrr}
v_1 \\
v_2 \\
v_3 \\
\end{array}\right]
=
\left[\begin{array}
{rrrr}
0 \\
0 \\
0 \\
\end{array}\right]
$$

$$\mathbf{v} = \left[\begin{array}
{rrrr}
2 \\
3 \\
0 \\
\end{array}\right]
$$

For $\lambda_1$ = 1, solve the following for **v**  

$$\left[\begin{array}
{rrrr}
0 & -2 & -3 \\
0 & -3 & -5 \\
0 & 0 & -5 \\
\end{array}\right]
\left[\begin{array}
{rrrr}
v_1 \\
v_2 \\
v_3 \\
\end{array}\right]
=
\left[\begin{array}
{rrrr}
0 \\
0 \\
0 \\
\end{array}\right]
$$

$$\mathbf{v} = \left[\begin{array}
{rrrr}
1 \\
0 \\
0 \\
\end{array}\right]
$$

In the last case, since the coefficient for $v_1$ is zero, $v_1$ can be any real number.  
